checksumpackage & uploadaccess: add logging

diff --git a/checksumpackage b/checksumpackage
--- a/checksumpackage
+++ b/checksumpackage
@@ -21,6 +21,14 @@ usage(){
 [ "${#}" = 0 ] && usage
 check_dependencies "${dependencies[@]}"
 
+cleanup(){
+    log -a "Process aborted"
+    exit 1
+}
+
+trap cleanup SIGHUP SIGINT SIGTERM
+log -b
+
 # local variables
 CHECKSUMNAME="checksum.md5"
 DFXMLNAME="dfxml.xml"
@@ -54,3 +62,4 @@ while [ "${*}" != "" ] ; do
     fi
     shift
 done
+log -e
diff --git a/uploadaccess b/uploadaccess
--- a/uploadaccess
+++ b/uploadaccess
@@ -11,6 +11,14 @@ if [ -z "$package_path" ]; then
     exit 1
 fi
 
+cleanup(){
+    log -a "Process aborted"
+    exit 1
+}
+
+trap cleanup SIGHUP SIGINT SIGTERM
+log -b
+
 package_dir=`dirname "$package_path"`
 pkgname=`basename "$package_path"`
 
@@ -63,3 +71,4 @@ fi
 [ ! -f "$package_path/metadata/premis.xml" ] && start_premis.sh "$package_path"
 premis_add_event.sh -x "$package_path/metadata/premis.xml" -i "$eventIdentifierType" -I "$eventIdentifierValue" -T "$eventType" -d "$eventDateTime" -D "$eventDetail" -E "$eventOutcome" -l "$agentIdentifierType" -L "$agentIdentifierValue" -r "$linkingAgentRole" -s "$sourceLinkingObjectIdentifierType" -S "$sourceLinkingObjectIdentifierValue" -o "URI" -O "./objects/access/${base%.*}.mp4"
 premis_add_agent.sh -x "$package_path/metadata/premis.xml" -i "$agentIdentifierType" -I "$agentIdentifierValue" -n "$agentName" -T "$agentType" -N "$agentNote" -l "$eventIdentifierType" -L "$eventIdentifierValue"
+log -e
