dpdpconfig: user pretty report option rather than echo

diff --git a/dpdpconfig b/dpdpconfig
--- a/dpdpconfig
+++ b/dpdpconfig
@@ -4,7 +4,7 @@
 CONFIG="Y"
 CONFIG_VERSION="1.0"
 scriptdir=$(dirname "$0")
-CONFIG_FILE="$scriptdir/dpdp.conf"
+. "$scriptdir/dpdpfunctions" || { echo "Missing '$scriptdir/dpdpfunctions'. Exiting." ; exit 1 ;};
 
 # local variables
 REQUIRED_VARIABLES=("PBCORE_USERNAME" "PBCORE_PASSWORD" "PROCESSDIR" "EMAIL_OUTCOME_TO")
@@ -25,14 +25,14 @@ if [ ! -f "$CONFIG_FILE" ] ; then
     done
 fi
 
-echo "Table of existing variables:"
+report -d "Table of existing variables:"
 for KEY in "${REQUIRED_VARIABLES[@]}" ; do
     VALUE=$(grep "^$KEY=" "$CONFIG_FILE" | cut -d= -f2)
     printf '\t%-25s %-40s\n' "$KEY" "$VALUE"
 done
 while true ; do
     EDITOPTION="Edit config file in nano"
-    echo "Edit a variable? "
+    report -q "Edit a variable? "
     PS3="Selection (enter by number)? "
     select CONFIG_KEY in "$EDITOPTION" "${REQUIRED_VARIABLES[@]}" "Quit"
     do
